package cmd

import (
	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

func init() {
	rootCmd.AddCommand(versionCmd)
}

var (
	versionString = "<none>"
	versionCmd    = &cobra.Command{
		Use:   "version",
		Short: "Displays the version of Ekara.",
		Run: func(cmd *cobra.Command, args []string) {
			color.New(color.FgHiWhite).Print("CLI executable version: ")
			color.New(color.FgCyan).Println(versionString)
			color.New(color.FgHiWhite).Print("Installer image: ")
			color.New(color.FgCyan).Println(starterImageName)
		},
	}
)
