package cmd

import (
	"github.com/ekara-platform/cli/common"
	"github.com/spf13/cobra"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

func init() {
	rootCmd.AddCommand(versionCmd)
}

var (
	versionString = "Unknown"
	versionCmd    = &cobra.Command{
		Use:   "version",
		Short: "Displays the version of Ekara and its installer.",
		Run: func(cmd *cobra.Command, args []string) {
			common.CliFeedbackNotifier.Info("CLI executable version: %s", versionString)
			common.CliFeedbackNotifier.Info("Installer image: %s", starterImageName)
		},
	}
)
